#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libx264
Version  : 0.161
Release  : 11
URL      : file:///aot/build/clearlinux/packages/libx264/libx264-v.tar.gz
Source0  : file:///aot/build/clearlinux/packages/libx264/libx264-v.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : ImageMagick-dev
BuildRequires : SDL2-dev
BuildRequires : Sphinx
BuildRequires : Z3-dev
BuildRequires : Z3-staticdev
BuildRequires : alsa-lib-dev
BuildRequires : alsa-lib-lib
BuildRequires : binutils
BuildRequires : binutils-dev
BuildRequires : binutils-staticdev
BuildRequires : brotli
BuildRequires : brotli-dev
BuildRequires : brotli-staticdev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-configure
BuildRequires : bzip2
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : cairo
BuildRequires : cairo-dev
BuildRequires : cuda
BuildRequires : cuda-dev
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : expat-dev
BuildRequires : findutils
BuildRequires : fontconfig-dev
BuildRequires : freetype-dev
BuildRequires : freetype-staticdev
BuildRequires : fribidi-dev
BuildRequires : fribidi-staticdev
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : glibc
BuildRequires : glibc-dev
BuildRequires : glibc-staticdev
BuildRequires : gmp
BuildRequires : gmp-dev
BuildRequires : gnutls
BuildRequires : gnutls-dev
BuildRequires : graphite-dev
BuildRequires : gsm-dev
BuildRequires : gsm-staticdev
BuildRequires : harfbuzz-dev
BuildRequires : harfbuzz-staticdev
BuildRequires : jack2-dev
BuildRequires : l-smash
BuildRequires : l-smash-dev
BuildRequires : l-smash-staticdev
BuildRequires : ladspa_sdk
BuildRequires : ladspa_sdk-bin
BuildRequires : ladspa_sdk-dev
BuildRequires : ladspa_sdk-lib
BuildRequires : libaom-dev
BuildRequires : libaom-staticdev
BuildRequires : libass-dev
BuildRequires : libass-lib
BuildRequires : libass-staticdev
BuildRequires : libatomic_ops-dev
BuildRequires : libatomic_ops-staticdev
BuildRequires : libbluray
BuildRequires : libbluray-dev
BuildRequires : libbluray-staticdev
BuildRequires : libcap-ng-dev
BuildRequires : libconfig-dev
BuildRequires : libconfig-staticdev
BuildRequires : libdav1d-dev
BuildRequires : libdav1d-staticdev
BuildRequires : libdrm
BuildRequires : libdrm-dev
BuildRequires : libdrm-lib
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libfdk_aac-dev
BuildRequires : libfdk_aac-staticdev
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcc1
BuildRequires : libidn2
BuildRequires : libidn2-dev
BuildRequires : libiec61883-dev
BuildRequires : libiec61883-staticdev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libmp3lame-dev
BuildRequires : libmp3lame-lib
BuildRequires : libmp3lame-staticdev
BuildRequires : libogg-dev
BuildRequires : libogg-staticdev
BuildRequires : libpng-dev
BuildRequires : libpng-staticdev
BuildRequires : libstdc++
BuildRequires : libtasn1-dev
BuildRequires : libtheora-dev
BuildRequires : libtheora-staticdev
BuildRequires : libunistring-dev
BuildRequires : libunistring-staticdev
BuildRequires : libva
BuildRequires : libva-dev
BuildRequires : libvdpau
BuildRequires : libvdpau-dev
BuildRequires : libvidstab-dev
BuildRequires : libvorbis-dev
BuildRequires : libvorbis-staticdev
BuildRequires : libvpx-dev
BuildRequires : libvpx-staticdev
BuildRequires : libwebp-dev
BuildRequires : libwebp-staticdev
BuildRequires : libx265
BuildRequires : libx265-dev
BuildRequires : libx265-lib
BuildRequires : libx265-staticdev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : libxvid
BuildRequires : libxvid-dev
BuildRequires : libxvid-staticdev
BuildRequires : libzimg-dev
BuildRequires : libzimg-staticdev
BuildRequires : mediasdk-dev
BuildRequires : mesa-dev
BuildRequires : mm-common-dev
BuildRequires : nasm
BuildRequires : nasm-bin
BuildRequires : ncurses-dev
BuildRequires : nettle
BuildRequires : nettle-dev
BuildRequires : nv-codec-headers-dev
BuildRequires : nvidia
BuildRequires : opencl-headers
BuildRequires : opencl-headers-dev
BuildRequires : openssl-dev
BuildRequires : opus-dev
BuildRequires : opus-staticdev
BuildRequires : p11-kit
BuildRequires : p11-kit-dev
BuildRequires : pcre-dev
BuildRequires : pcre-staticdev
BuildRequires : pixman
BuildRequires : pixman-dev
BuildRequires : pixman-staticdev
BuildRequires : pkgconfig(Magick++)
BuildRequires : pkgconfig(MagickCore)
BuildRequires : pkgconfig(MagickWand)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(aom)
BuildRequires : pkgconfig(atomic_ops)
BuildRequires : pkgconfig(bzip2)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-egl)
BuildRequires : pkgconfig(cairo-fc)
BuildRequires : pkgconfig(cairo-ft)
BuildRequires : pkgconfig(cairo-gl)
BuildRequires : pkgconfig(cairo-glx)
BuildRequires : pkgconfig(cairo-gobject)
BuildRequires : pkgconfig(cairo-pdf)
BuildRequires : pkgconfig(cairo-png)
BuildRequires : pkgconfig(cairo-ps)
BuildRequires : pkgconfig(cairo-script)
BuildRequires : pkgconfig(cairo-svg)
BuildRequires : pkgconfig(cairo-xcb)
BuildRequires : pkgconfig(cairo-xcb-shm)
BuildRequires : pkgconfig(cairo-xlib)
BuildRequires : pkgconfig(cairo-xlib-xcb)
BuildRequires : pkgconfig(cairo-xlib-xrender)
BuildRequires : pkgconfig(dav1d)
BuildRequires : pkgconfig(dbus-c++-1)
BuildRequires : pkgconfig(dbus-c++-ecore-1)
BuildRequires : pkgconfig(dbus-c++-glib-1)
BuildRequires : pkgconfig(dri)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(fdk-aac)
BuildRequires : pkgconfig(ffnvcodec)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(fribidi)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(hogweed)
BuildRequires : pkgconfig(jack)
BuildRequires : pkgconfig(lame)
BuildRequires : pkgconfig(libass)
BuildRequires : pkgconfig(libbluray)
BuildRequires : pkgconfig(libbrotlicommon)
BuildRequires : pkgconfig(libbrotlidec)
BuildRequires : pkgconfig(libbrotlienc)
BuildRequires : pkgconfig(libconfig)
BuildRequires : pkgconfig(libconfig++)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdvbv5)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(libidn2)
BuildRequires : pkgconfig(liblsmash)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libmfx)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(libpcre16)
BuildRequires : pkgconfig(libpcre32)
BuildRequires : pkgconfig(libpcrecpp)
BuildRequires : pkgconfig(libpcreposix)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libpostproc)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libraw1394)
BuildRequires : pkgconfig(librtmp)
BuildRequires : pkgconfig(libswresample)
BuildRequires : pkgconfig(libswscale)
BuildRequires : pkgconfig(libtasn1)
BuildRequires : pkgconfig(libv4l1)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(libv4l2rds)
BuildRequires : pkgconfig(libv4lconvert)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(libwebpdecoder)
BuildRequires : pkgconfig(libwebpdemux)
BuildRequires : pkgconfig(libwebpmux)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(opus)
BuildRequires : pkgconfig(p11-kit-1)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(readline)
BuildRequires : pkgconfig(sdl2)
BuildRequires : pkgconfig(speex)
BuildRequires : pkgconfig(theora)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(vdpau)
BuildRequires : pkgconfig(vorbis)
BuildRequires : pkgconfig(vpx)
BuildRequires : pkgconfig(xdg-desktop-portal)
BuildRequires : pkgconfig(zimg)
BuildRequires : pkgconfig(zlib)
BuildRequires : pulseaudio-dev
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : rtmpdump
BuildRequires : rtmpdump-dev
BuildRequires : rtmpdump-staticdev
BuildRequires : snappy-dev
BuildRequires : snappy-staticdev
BuildRequires : speex-dev
BuildRequires : speex-staticdev
BuildRequires : speexdsp-dev
BuildRequires : speexdsp-staticdev
BuildRequires : texinfo
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-staticdev
BuildRequires : v4l-utils
BuildRequires : v4l-utils-dev
BuildRequires : valgrind
BuildRequires : valgrind-dev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : yaml-cpp
BuildRequires : yaml-cpp-dev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%prep
%setup -q -n libx264
cd %{_builddir}/libx264

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1621155588
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fPIC -Wl,-z,max-page-size=0x1000 -fvisibility=hidden -flto-partition=none
# gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export CXXFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export FCFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export FFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -Wl,--build-id=sha1"
export CFFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export LDFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -Wl,--build-id=sha1"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
## altflags1 end
%configure --enable-shared --enable-static --enable-asm --enable-lto --enable-pic --bit-depth=all --enable-lsmash
## make_prepend content
#find . -type f -name 'Makefile*' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
#find . -type f -name '*.mak' -exec sed -i 's/\-fPIC/\-fpic/g' {} \;
## make_prepend end
make  %{?_smp_mflags}  fprofiled VIDS="/opt/fprofile/harry.y4m /opt/fprofile/eyes.y4m /opt/fprofile/allied.y4m /opt/fprofile/gerra.y4m /opt/fprofile/harry2.y4m" V=1 VERBOSE=1


%install
export SOURCE_DATE_EPOCH=1621155588
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
